FROM python
#FROM powerdatahub/great-expectations-docker:0.8.7
WORKDIR /flaskapi
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install pandas

COPY . .
ENV FLASK_APP=app
CMD ["python","main.py"]